# Generated by Django 5.2.13 on 2026-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_alter_customuser_date_joined_alter_customuser_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
