# Generated by Django 5.2.13 on 2026-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Administrateur", "Administrateur"),
                    ("Inspecteur IEF", "Inspecteur IEF"),
                    ("Directeur", "Directeur"),
                    ("Enseignant", "Enseignant"),
                ],
                max_length=30,
            ),
        ),
    ]
