# Generated by Django 5.2.13 on 2026-04-29 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ecole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ancien_code_ecole",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nouveau_code_ecole", models.CharField(max_length=50, unique=True)),
                ("nom_ecole", models.CharField(max_length=200)),
                (
                    "ancien_nom_ecole",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_creation", models.DateField(blank=True, null=True)),
                ("statut", models.CharField(blank=True, max_length=50, null=True)),
                ("loc_admin", models.CharField(blank=True, max_length=100, null=True)),
                ("loc_scol", models.CharField(blank=True, max_length=100, null=True)),
                ("zone", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["nouveau_code_ecole"],
                        name="dashboard_e_nouveau_bfcec6_idx",
                    ),
                    models.Index(
                        fields=["nom_ecole"], name="dashboard_e_nom_eco_f2d0d7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero_reg", models.CharField(max_length=50, unique=True)),
                (
                    "kobo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("nom_prenom", models.CharField(max_length=200)),
                ("nni", models.CharField(max_length=50, unique=True)),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("classe", models.CharField(blank=True, max_length=50, null=True)),
                ("tel", models.CharField(blank=True, max_length=20, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                ("enseignant", models.CharField(blank=True, max_length=200, null=True)),
                ("signature", models.URLField(blank=True, null=True)),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eleves",
                        to="dashboard.ecole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbsenceQuotidienneEleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kobo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("date_absence", models.DateField()),
                ("total_absences", models.IntegerField(default=0)),
                ("periodes", models.CharField(blank=True, max_length=100, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                ("enseignant", models.CharField(blank=True, max_length=200, null=True)),
                ("signature", models.URLField(blank=True, null=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences_quotidiennes",
                        to="dashboard.eleve",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbsenceMensuelleEleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kobo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "mois",
                    models.DateField(
                        help_text="Stocke le 1er jour du mois concerné (ex: 2023-10-01)"
                    ),
                ),
                ("total_absences", models.IntegerField(default=0)),
                ("observations", models.TextField(blank=True, null=True)),
                ("enseignant", models.CharField(blank=True, max_length=200, null=True)),
                ("signature", models.URLField(blank=True, null=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences_mensuelles",
                        to="dashboard.eleve",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero_reg", models.CharField(max_length=50, unique=True)),
                (
                    "kobo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("nom_prenom", models.CharField(max_length=200)),
                ("nni", models.CharField(max_length=50)),
                ("mle", models.CharField(max_length=50)),
                ("langue_travail", models.CharField(max_length=50)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=10
                    ),
                ),
                ("tel", models.CharField(blank=True, max_length=20, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "directeur_nom",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("signature_cachet", models.URLField(blank=True, null=True)),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enseignants",
                        to="dashboard.ecole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbsenceQuotidienneEnseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kobo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("date_absence", models.DateField()),
                ("abs_justifiees", models.IntegerField(default=0)),
                ("abs_non_justifiees", models.IntegerField(default=0)),
                ("periodes", models.CharField(blank=True, max_length=100, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "directeur_nom",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("signature_cachet", models.URLField(blank=True, null=True)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences_quotidiennes",
                        to="dashboard.enseignant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbsenceMensuelleEnseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kobo_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "mois",
                    models.DateField(help_text="Stocke le 1er jour du mois concerné"),
                ),
                ("abs_justifiees", models.IntegerField(default=0)),
                ("abs_non_justifiees", models.IntegerField(default=0)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "directeur_nom",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("signature_cachet", models.URLField(blank=True, null=True)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences_mensuelles",
                        to="dashboard.enseignant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="eleve",
            index=models.Index(
                fields=["numero_reg"], name="dashboard_e_numero__3379a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eleve",
            index=models.Index(fields=["ecole"], name="dashboard_e_ecole_i_578eeb_idx"),
        ),
        migrations.AddIndex(
            model_name="absencequotidienneeleve",
            index=models.Index(
                fields=["date_absence"], name="dashboard_a_date_ab_a18afa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="absencequotidienneeleve",
            unique_together={("eleve", "date_absence")},
        ),
        migrations.AddIndex(
            model_name="absencemensuelleeleve",
            index=models.Index(fields=["mois"], name="dashboard_a_mois_aae213_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="absencemensuelleeleve",
            unique_together={("eleve", "mois")},
        ),
        migrations.AddIndex(
            model_name="enseignant",
            index=models.Index(
                fields=["numero_reg"], name="dashboard_e_numero__3ac2c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enseignant",
            index=models.Index(fields=["ecole"], name="dashboard_e_ecole_i_02b1f3_idx"),
        ),
        migrations.AddIndex(
            model_name="absencequotidienneenseignant",
            index=models.Index(
                fields=["date_absence"], name="dashboard_a_date_ab_0fd658_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="absencequotidienneenseignant",
            unique_together={("enseignant", "date_absence")},
        ),
        migrations.AddIndex(
            model_name="absencemensuelleenseignant",
            index=models.Index(fields=["mois"], name="dashboard_a_mois_0593cb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="absencemensuelleenseignant",
            unique_together={("enseignant", "mois")},
        ),
    ]
